language: java

matrix:
  include:
  - os: linux
    dist: trusty
    jdk: openjdk11
    env:
      - JDK_HOME=~/openjdk11 # force launching JLS using JDK11
  - os: osx
    osx_image: xcode10.1
    jdk: oraclejdk11

addons:
  apt:
    packages:
    - libsecret-1-dev

before_install:
  - |
    if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9"
      export DISPLAY=':99.0'
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      sleep 3
    fi
  - nvm install 12
  - nvm use 12

install:
- npm install -g vsce
- npm install -g typescript
- npm install -g gulp
- npm install

script:
- gulp tslint
- gulp checkstyle
- gulp build_server
- vsce package
- npm test

after_failure:
- | 
  if [ "$TRAVIS_OS_NAME" = "osx" ]; then 
    find $HOME/Library/Application\ Support/Code/User/workspaceStorage/*/redhat.java/jdt_ws/.metadata/.log -print -exec cat '{}' \;;
  fi;
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then
    find $HOME/.config/Code/User/workspaceStorage/*/redhat.java/jdt_ws/.metadata/.log -print -exec cat '{}' \;;
  fi;
